In [1]:
import pandas as pd
df = pd.read_csv(r'G:\Datasets\housing.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [2]:
df = df.dropna()
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [3]:
df = df.drop('ocean_proximity', axis=1)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-1.327314,1.051717,0.982163,-0.803813,-0.970325,-0.973320,-0.976833,2.345163,2.128819
1,-1.322323,1.042355,-0.606210,2.042130,1.348276,0.861339,1.670373,2.332632,1.313626
2,-1.332305,1.037674,1.855769,-0.535189,-0.825561,-0.819769,-0.843427,1.782939,1.258183
3,-1.337296,1.037674,1.855769,-0.623510,-0.718768,-0.765056,-0.733562,0.932970,1.164622
4,-1.337296,1.037674,1.855769,-0.461970,-0.611974,-0.758879,-0.628930,-0.013143,1.172418
...,...,...,...,...,...,...,...,...,...
20428,-0.758318,1.800677,-0.288535,-0.444580,-0.388895,-0.511787,-0.443207,-1.216727,-1.115492
20429,-0.818212,1.805358,-0.844466,-0.887557,-0.920488,-0.943315,-1.008223,-0.692044,-1.124155
20430,-0.823203,1.777272,-0.923885,-0.175042,-0.125472,-0.368826,-0.173778,-1.143171,-0.992477
20431,-0.873115,1.777272,-0.844466,-0.355344,-0.305834,-0.603564,-0.393506,-1.055136,-1.058316
20432,-0.833186,1.749186,-1.003304,0.067955,0.185416,-0.033487,0.079956,-0.780606,-1.017600

In [5]:
X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Linear Regression Using Sklearn

In [7]:
from sklearn.linear_model import SGDRegressor
model = SGDRegressor(max_iter=5000, tol=1e-3)
# Train the model
model = model.fit(X_train, y_train)

In [8]:
from sklearn.metrics import mean_squared_error, r2_score

# --- Make predictions ---
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# --- Calculate MSE ---
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)

# --- Calculate R² ---
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# --- Display results neatly ---
print("Model Performance:")
print(f"  Training MSE       : {train_mse:.4f}")
print(f"  Testing MSE        : {test_mse:.4f}")
print(f"  Training R-squared : {train_r2:.4f}")
print(f"  Testing R-squared  : {test_r2:.4f}")

Model Performance:
  Training MSE       : 0.3619
  Testing MSE        : 0.3697
  Training R-squared : 0.6357
  Testing R-squared  : 0.6397

Linear Regression (My own Algorithm)

In [9]:
import numpy as np

class ManualLinearRegression:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape


        self.weights = np.zeros(n_features)
        self.bias = 0


        X = X.values if isinstance(X, pd.DataFrame) else X
        y = y.values if isinstance(y, pd.Series) else y



        for i in range(self.n_iterations):

            y_predicted = np.dot(X, self.weights) + self.bias


            dw = (1/n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1/n_samples) * np.sum(y_predicted - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        X = X.values if isinstance(X, pd.DataFrame) else X
        return np.dot(X, self.weights) + self.bias


def mean_squared_error_manual(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

manual_model = ManualLinearRegression(learning_rate=0.01, n_iterations=5000)
manual_model.fit(X_train, y_train)

# Make predictions with the manual model
y_train_pred_manual = manual_model.predict(X_train)
y_test_pred_manual = manual_model.predict(X_test)

train_mse_manual = mean_squared_error_manual(y_train, y_train_pred_manual)
test_mse_manual = mean_squared_error_manual(y_test, y_test_pred_manual)

In [10]:
# Print the MSE for the manual model
print("Manual Linear Regression Model Performance (My own algorithm):")
print(f"  Training MSE: {train_mse_manual:.4f}")
print(f"  Testing MSE : {test_mse_manual:.4f}")

Manual Linear Regression Model Performance (My own algorithm):
  Training MSE: 0.3619
  Testing MSE : 0.3694

Student performance dataset

In [11]:
df2 = pd.read_csv(r'G:\Datasets\Student_Performance.csv')
df2

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [12]:
df2['Extracurricular Activities'] = df2['Extracurricular Activities'].map({'Yes': 1, 'No': 0})
df2

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [13]:
# Scale df2 (excluding the binary extracurricular activities column)
scaler2 = StandardScaler()

# Get column names to preserve order
column_names = df2.columns

# Store the 'Extracurricular Activities' column separately
extracurricular = df2[['Extracurricular Activities']]

# Scale only the numerical columns
numerical_cols = df2.drop('Extracurricular Activities', axis=1).columns
df2_scaled = pd.DataFrame(
    scaler2.fit_transform(df2[numerical_cols]),
    columns=numerical_cols
)

# Add back the 'Extracurricular Activities' column
df2_scaled['Extracurricular Activities'] = extracurricular.values

# Reorder columns to match original order
df2 = df2_scaled[column_names]
df2

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,0.775188,1.704176,1,1.456205,-1.249754,1.862167
1,-0.383481,0.723913,0,-1.492294,-0.900982,0.508818
2,1.161410,-1.063626,1,0.276805,-0.900982,-0.532220
3,0.002742,-1.005963,1,-0.902594,-0.900982,-1.000687
4,0.775188,0.320275,0,0.866505,0.145333,0.560870
...,...,...,...,...,...,...
9995,-1.542149,-1.178951,1,-1.492294,-0.900982,-1.677362
9996,0.775188,-0.314013,1,0.866505,0.145333,0.144454
9997,0.388965,0.781575,1,0.866505,0.145333,0.977285
9998,1.547633,1.588851,1,0.276805,-1.598526,2.070374
9999,0.775188,0.262612,0,0.866505,-1.249754,0.456766

In [14]:
# Split df2 into features and target
Xdf2 = df2.drop('Performance Index', axis=1)
ydf2 = df2['Performance Index']

# Create train/test split for df2
X_train_df2, X_test_df2, y_train_df2, y_test_df2 = train_test_split(Xdf2, ydf2, test_size=0.2, random_state=42)

Linear Regression Using Sklearn (Student Dataset)

In [15]:
# Train sklearn model on df2
model_df2 = SGDRegressor(max_iter=5000, tol=1e-3)
model_df2.fit(X_train_df2, y_train_df2)

SGDRegressor(max_iter=5000)

In [16]:
# Make predictions with sklearn model on df2
y_train_pred_df2 = model_df2.predict(X_train_df2)
y_test_pred_df2 = model_df2.predict(X_test_df2)

# Calculate metrics for df2
train_mse_df2 = mean_squared_error(y_train_df2, y_train_pred_df2)
test_mse_df2 = mean_squared_error(y_test_df2, y_test_pred_df2)
train_r2_df2 = r2_score(y_train_df2, y_train_pred_df2)
test_r2_df2 = r2_score(y_test_df2, y_test_pred_df2)

print("Sklearn Model Performance (Student Dataset):")
print(f"  Training MSE       : {train_mse_df2:.4f}")
print(f"  Testing MSE        : {test_mse_df2:.4f}")
print(f"  Training R-squared : {train_r2_df2:.4f}")
print(f"  Testing R-squared  : {test_r2_df2:.4f}")

Sklearn Model Performance (Student Dataset):
  Training MSE       : 0.0113
  Testing MSE        : 0.0111
  Training R-squared : 0.9887
  Testing R-squared  : 0.9889

Linear Regression (My own Algorithm) on Student Dataset

In [17]:
# Train manual model on df2
manual_model_df2 = ManualLinearRegression(learning_rate=0.01, n_iterations=5000)
manual_model_df2.fit(X_train_df2, y_train_df2)

# Make predictions with the manual model
y_train_pred_manual_df2 = manual_model_df2.predict(X_train_df2)
y_test_pred_manual_df2 = manual_model_df2.predict(X_test_df2)

# Calculate MSE
train_mse_manual_df2 = mean_squared_error_manual(y_train_df2, y_train_pred_manual_df2)
test_mse_manual_df2 = mean_squared_error_manual(y_test_df2, y_test_pred_manual_df2)

print("Manual Linear Regression Model Performance (Student Dataset):")
print(f"  Training MSE: {train_mse_manual_df2:.4f}")
print(f"  Testing MSE : {test_mse_manual_df2:.4f}")

Manual Linear Regression Model Performance (Student Dataset):
  Training MSE: 0.0113
  Testing MSE : 0.0111

Salary Dataset

In [18]:
df3 = pd.read_csv('G:\Datasets\Salary_dataset.csv')
df3

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Basil\AppData\Local\Temp\ipykernel_34540\1146288929.py:1: SyntaxWarning: invalid escape sequence '\D'
  df3 = pd.read_csv('G:\Datasets\Salary_dataset.csv')

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [19]:
df3 = df3.drop('Unnamed: 0', axis=1)
df3

    YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [20]:
# If df3 was accidentally converted to a numpy array earlier, re-load the original CSV to restore column names
import numpy as np

if isinstance(df3, np.ndarray):
	df3 = pd.read_csv(r'G:\Datasets\Salary_dataset.csv')
	df3 = df3.drop('Unnamed: 0', axis=1)

Scaler3 = StandardScaler()
# keep df3 as a DataFrame after scaling so we can use DataFrame methods like .drop()
df3 = pd.DataFrame(Scaler3.fit_transform(df3), columns=df3.columns)
df3

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [21]:
Xdf3 = df3.drop('Salary', axis=1)
ydf3 = df3['Salary']
X_train_df3, X_test_df3, y_train_df3, y_test_df3 = train_test_split(Xdf3, ydf3, test_size=0.2, random_state=42)

Linear Regression with Sklearn (Salary Dataset)

In [22]:
model3 = SGDRegressor(max_iter=5000, tol=1e-3)
model3.fit(X_train_df3, y_train_df3)

SGDRegressor(max_iter=5000)

In [23]:
y_train_pred_df3 = model3.predict(X_train_df3)
y_test_pred_df3 = model3.predict(X_test_df3)

# Calculate metrics for df3
train_mse_df3 = mean_squared_error(y_train_df3, y_train_pred_df3)
test_mse_df3 = mean_squared_error(y_test_df3, y_test_pred_df3)
train_r2_df3 = r2_score(y_train_df3, y_train_pred_df3)
test_r2_df3 = r2_score(y_test_df3, y_test_pred_df3)

print("Sklearn Model Performance (Sklearn algorithm):")
print(f"  Training MSE       : {train_mse_df3:.4f}")
print(f"  Testing MSE        : {test_mse_df3:.4f}")
print(f"  Training R-squared : {train_r2_df3:.4f}")
print(f"  Testing R-squared  : {test_r2_df3:.4f}")

Sklearn Model Performance (Sklearn algorithm):
  Training MSE       : 0.0496
  Testing MSE        : 0.0821
  Training R-squared : 0.9529
  Testing R-squared  : 0.8833

Linear Regression using my own algorithm (Salary Dataset)

In [24]:
manual_model_df3 = ManualLinearRegression(learning_rate=0.01, n_iterations=5000)
manual_model_df3.fit(X_train_df3, y_train_df3)

# Make predictions with the manual model
y_train_pred_manual_df3 = manual_model_df3.predict(X_train_df3)
y_test_pred_manual_df3 = manual_model_df3.predict(X_test_df3)

# Calculate MSE
train_mse_manual_df3 = mean_squared_error_manual(y_train_df3, y_train_pred_manual_df3)
test_mse_manual_df3 = mean_squared_error_manual(y_test_df3, y_test_pred_manual_df3)

print("Manual Linear Regression Model Performance (My own algorithm):")
print(f"  Training MSE: {train_mse_manual_df3:.4f}")
print(f"  Testing MSE : {test_mse_manual_df3:.4f}")

Manual Linear Regression Model Performance (My own algorithm):
  Training MSE: 0.0373
  Testing MSE : 0.0686

Life Expectancy Dataset

In [25]:
df4 = pd.read_csv('G:\Datasets\Life_Expectancy_Data.csv')
df4

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Basil\AppData\Local\Temp\ipykernel_34540\1090717571.py:1: SyntaxWarning: invalid escape sequence '\D'
  df4 = pd.read_csv('G:\Datasets\Life_Expectancy_Data.csv')

,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [26]:
df4['Status'] = df4['Status'].map({'Developed': 1, 'Developing': 0})
df4

,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,0,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,0,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,0,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,0,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,0,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,0,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,2003,0,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,2002,0,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,2001,0,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,2000,0,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [27]:
# Impute missing numeric values in df4 using KNNImputer
from sklearn.impute import KNNImputer
import numpy as np

# Identify numeric columns
num_cols = df4.select_dtypes(include=[np.number]).columns

imputer = KNNImputer(n_neighbors=5)
df4_num = pd.DataFrame(
    imputer.fit_transform(df4[num_cols]),
    columns=num_cols,
    index=df4.index
)

# Replace numeric columns in the original dataframe with imputed values
df4.loc[:, num_cols] = df4_num

# Show a quick summary to verify no missing numeric values remain
print('Numeric columns imputed. Missing values per column:')
print(df4[num_cols].isna().sum())
df4

Numeric columns imputed. Missing values per column:
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,0,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,0,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,0,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,0,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,0,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,0,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,2003,0,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,2002,0,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,2001,0,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,2000,0,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [28]:
Scaler4 = StandardScaler()

# If df4 is a numpy array (no .columns), recover column names from known variables (num_cols or df4_num),
# otherwise use df4.columns directly.
if isinstance(df4, np.ndarray):
	if 'num_cols' in globals():
		cols = list(num_cols)
	elif 'df4_num' in globals():
		cols = list(df4_num.columns)
	else:
		cols = [f'col_{i}' for i in range(df4.shape[1])]
	df4 = pd.DataFrame(Scaler4.fit_transform(df4), columns=cols)
else:
	df4 = pd.DataFrame(Scaler4.fit_transform(df4), columns=df4.columns)

df4

,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,1.621762,-0.459399,-0.445530,0.792042,0.268824,-1.153285,-0.335570,-0.677073,-0.110384,-0.959556,...,-3.276748,0.912279,-0.733608,-0.323445,-0.462016,0.390002,2.803776,2.764720,-0.701989,-0.554347
1,1.404986,-0.459399,-0.981757,0.856495,0.285786,-1.153285,-0.334441,-0.804497,-0.168124,-0.984586,...,-1.051277,0.920505,-0.860439,-0.323445,-0.459885,-0.212490,2.871910,2.809256,-0.716373,-0.584353
2,1.188210,-0.459399,-0.981757,0.832325,0.302749,-1.153285,-0.334594,-0.719548,-0.173531,-1.009615,...,-0.880087,0.899940,-0.775885,-0.323445,-0.458458,0.353847,2.917333,2.853791,-0.745142,-0.614360
3,0.971434,-0.459399,-1.023814,0.864552,0.328193,-1.153285,-0.332096,-0.592123,0.032045,-1.034644,...,-0.666100,1.060346,-0.649054,-0.323445,-0.455594,-0.151727,2.962755,2.920594,-0.778705,-0.644366
4,0.754658,-0.459399,-1.055356,0.888722,0.345155,-1.153285,-0.367862,-0.549648,0.051757,-1.054668,...,-0.623302,0.793003,-0.606777,-0.323445,-0.501040,-0.164682,3.030889,2.965129,-0.821857,-0.734386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,-0.762774,-0.459399,-2.621979,4.498079,-0.028022,-0.055457,-0.371433,-0.549648,-0.208332,-0.559087,...,-0.666100,0.488644,-0.733608,6.275044,-0.471751,0.012030,1.032289,1.005581,-1.047210,-0.824406
2934,-0.979550,-0.459399,-2.600951,4.433626,-0.036503,-0.131169,-0.371433,-3.140613,-0.123991,-0.579111,...,-3.233950,0.237754,-0.606777,6.885650,-0.471827,0.009440,1.123135,1.116919,-0.994468,-0.734386
2935,-1.196326,-0.459399,-2.569408,-0.738712,-0.044984,-0.037791,-0.371433,-0.337274,-0.184521,-0.599134,...,-0.409315,0.241867,-0.479946,7.496256,-0.501504,-0.216134,-0.830042,-0.798094,-0.951315,-0.584353
2936,-1.413102,-0.459399,-2.516837,4.199985,-0.044984,-0.721725,-0.371433,-0.209850,-0.164897,-0.619158,...,-0.280922,0.089687,-0.310838,7.949287,-0.464690,0.004612,-0.739197,-0.709023,-0.951315,-0.644366
2937,-1.629878,-0.459399,-2.443237,4.030796,-0.053466,-0.731820,-0.371433,-0.082425,-0.081689,-0.639181,...,-0.195327,0.476305,-0.184007,8.225045,-0.464782,0.002017,1.395671,1.406398,-0.917752,-0.644366

In [29]:
Xdf4 = df4.drop('Life expectancy ', axis=1)
ydf4 = df4['Life expectancy ']
X_train_df4, X_test_df4, y_train_df4, y_test_df4 = train_test_split(Xdf4, ydf4, test_size=0.2, random_state=42)

Linear Regression with Sklearn (Life Expectancy Dataset)

In [30]:
model4 = SGDRegressor(max_iter=5000, tol=1e-3)
model4.fit(X_train_df4, y_train_df4)

SGDRegressor(max_iter=5000)

In [31]:
# Calculate training and testing MSE for model4
y_train_pred_df4 = model4.predict(X_train_df4)
y_test_pred_df4 = model4.predict(X_test_df4)

train_mse_df4 = mean_squared_error(y_train_df4, y_train_pred_df4)
test_mse_df4 = mean_squared_error(y_test_df4, y_test_pred_df4)

print(f"Training MSE (model4): {train_mse_df4:.4f}")
print(f"Testing MSE (model4): {test_mse_df4:.4f}")

Training MSE (model4): 0.1822
Testing MSE (model4): 0.1609

Linear Regression using my own algorithm

In [32]:
manual_model_df4 = ManualLinearRegression(learning_rate=0.01, n_iterations=5000)
manual_model_df4.fit(X_train_df4, y_train_df4)

# Make predictions with the manual model
y_train_pred_manual_df4 = manual_model_df4.predict(X_train_df4)
y_test_pred_manual_df4 = manual_model_df4.predict(X_test_df4)

# Calculate MSE
train_mse_manual_df4 = mean_squared_error_manual(y_train_df4, y_train_pred_manual_df4)
test_mse_manual_df4 = mean_squared_error_manual(y_test_df4, y_test_pred_manual_df4)

print("Manual Linear Regression Model Performance (My own algorithm):")
print(f"  Training MSE: {train_mse_manual_df4:.4f}")
print(f"  Testing MSE : {test_mse_manual_df4:.4f}")

Manual Linear Regression Model Performance (My own algorithm):
  Training MSE: 0.1800
  Testing MSE : 0.1596